version: '3'

services:
  tests:
      build:
        context: ./backend
        dockerfile: Dockerfile.test
      container_name: backend-tests-nocontrole   
      ports:
        - '4000:4000'
      volumes:
        - ./backend:/app
        - /app/node_modules
      depends_on:
        - nocontrole_mysql_database 
      networks:
        - nocontrole-network
  nocontrole_mysql_database:
    image: mysql
    container_name: nocontrole_database
    environment:
        MYSQL_ROOT_PASSWORD: 12345678  
        MYSQL_DATABASE: nocontrole  
        MYSQL_USER: nocontrole  
        MYSQL_PASSWORD: 12345678 
    restart: always
    volumes:
        - ./database:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
        - nocontrole-network


networks:
  nocontrole-network:
    driver: bridge
