version: '3'

services:
  backend:
      build: 
        context: .
        dockerfile: Dockerfile  
        target: ${NODE_ENV}
      image: backend-nocontrole 
      container_name: backend-nocontrole   
      environment:
        - TZ=America/Bahia
      ports:
        - '4000:4000'
      volumes:
        - .:/app
      depends_on:
        - nocontrole_database 
        - studio
      networks:
        - nocontrole-network

  
  nocontrole_database:
    image: postgres
    container_name: nocontrole_database
    env_file:
      - .env
    
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
  studio:
    build:
        context: .
        target: ${NODE_ENV}
    container_name: prisma_studio
    command: bash -c "npx prisma generate && npx prisma migrate deploy && yarn seed && npx prisma studio"
    volumes:
        - .:/app
    ports:
       - '5555:5555'
    depends_on:
        - nocontrole_database
    networks:
        - nocontrole-network


networks:
  nocontrole-network:
    driver: bridge
