version: '3'

services:
  backend:
      build: 
        context: .
        dockerfile: Dockerfile  
        target: ${NODE_ENV}
      image: backend-nocontrole 
      container_name: backend-nocontrole   
      environment:
        - TZ=America/Bahia
      ports:
        - '4000:4000'
      volumes:
        - .:/app
      depends_on:
        - nocontrole_database 
        - studio
      networks:
        - nocontrole-network

  
  nocontrole_database:
    image: mysql:8.0
    container_name: nocontrole_database
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME} 
        MYSQL_PASSWORD: ${DB_PASSWORD} 
    restart: always
    volumes:
        - ./database:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
        - nocontrole-network
  studio:
    build:
        context: .
        target: ${NODE_ENV}
    container_name: prisma_studio
    command: bash -c "npx prisma generate && npx prisma studio"
    volumes:
        - .:/app
    ports:
       - '5555:5555'
    depends_on:
        - nocontrole_database
    networks:
        - nocontrole-network


networks:
  nocontrole-network:
    driver: bridge
