version: '3'

services:
  backend:
      build: 
        context: ./backend
        dockerfile: Dockerfile  
        target: ${NODE_ENV}
      image: backend-nocontrole 
      container_name: backend-nocontrole   
      environment:
        - TZ=America/Bahia
      ports:
        - '4000:4000'
      volumes:
        - ./backend:/app
      depends_on:
        - nocontrole_mysql_database 
        - studio
      networks:
        - nocontrole-network

        
  app-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${NODE_ENV}
    image: next-app
    container_name: next-app
    volumes:
      - ./frontend:/app
      - ./app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    networks:
        - nocontrole-network


  nocontrole_mysql_database:
    image: mysql:8.0
    container_name: nocontrole_database
    environment:
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME} 
        MYSQL_PASSWORD: ${DB_PASSWORD} 
    restart: always
    volumes:
        - ./database:/var/lib/mysql
    ports:
        - "3306:3306"
    networks:
        - nocontrole-network
  studio:
    build:
        context: ./backend
        target: ${NODE_ENV}
    container_name: prisma_studio
    command: bash -c "npx prisma generate && npx prisma studio"
    volumes:
        - ./backend:/app
    ports:
       - '5555:5555'
    depends_on:
        - nocontrole_mysql_database
    networks:
        - nocontrole-network
  migration:
    build:
        context: ./backend
        target: ${NODE_ENV}
    container_name: prisma_migration
    command: bash -c "npx prisma migrate dev && yarn seed && npx prisma generate"
    volumes:
        - ./backend:/app
    depends_on:
        - nocontrole_mysql_database
        - backend
    networks:
        - nocontrole-network


networks:
  nocontrole-network:
    driver: bridge
