name: remote ssh command using ssh key
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: cd no-controle && git pull https://${{secrets.PAT}}@github.com/camargosproj/no-controle.git test-sic && yarn build && pm2 restart 1
